-- IT HELP DESK DATABASE

-- Table Role
CREATE TABLE "role" (
    "Id" SERIAL PRIMARY KEY,
    "RoleName" CHRACTER VARYING(150) NOT NULL UNIQUE,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Table User
CREATE TABLE "user" (
    "ID" SERIAL PRIMARY KEY,
    "FullName" VARCHAR(150) NOT NULL,
    "Email" VARCHAR(150) NOT NULL UNIQUE,
    "PasswordHash" TEXT NOT NULL,
    "RoleId" INT NOT NULL,
    "IsActive" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    "UpdatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);